### ISSUE TITLE
如何调用？

### ISSUE THREAD

**Issue by leosteven2018** [luo3house/flutter_vant#3]
我拉取了demo，运行成功。但配置改成 flutter_vantui: ^0.0.1就运行不了，只能用本地的vantui文件夹中的组件

**Comment by luo3house** [comment]
hi， 0.0.1 是前了许多的版本。可用 git+ref 的方式获取最新的修改。e.g.

```yaml
flutter_vantui:
    git:
      url: https://github.com/luo3house/flutter_vant
      path: vantui
      ref: e10152b9c63609187e954687bb04400872622624
```
